import { Doughnut } from './app/shared/models/Doughnut';


export const sample_doughnuts: Doughnut[] = [
    {
        id: '1',
        name: 'Suger',
        price: 2,
        favorite: false,
        stars: 5.0,
        imageUrl: 'assets/images/d3.jpg',
        origins: ['italy'],
        cookTime: '10-15',
    },
    {
        id: '2',
        name: 'Homer',
        price: 1.5,
        favorite: false,
        stars: 4.0,
        imageUrl: 'assets/images/d4.jpg',
        origins: ['italy'],
        cookTime: '10-15',
    },
    {
        id: '3',
        name: 'Chocolate',
        price: 2,
        favorite: true,
        stars: 5.0,
        imageUrl: 'assets/images/d21.jpg',
        origins: ['italy'],
        cookTime: '10-15',
    },
    {
        id: '4',
        name: 'Jam',
        price: 2,
        favorite: false,
        stars: 5.0,
        imageUrl: 'assets/images/d17.jpg',
        origins: ['italy'],
        cookTime: '15-20',
    },
    {
        id: '5',
        name: 'Chocolate',
        price: 2,
        favorite: false,
        stars: 5.0,
        imageUrl: 'assets/images/d18.jpg',
        origins: ['italy'],
        cookTime: '10-15',
    },
    {
        id: '6',
        name: 'Matcha',
        price: 2,
        favorite: false,
        stars: 5.0,
        imageUrl: 'assets/images/d7.jpg',
        origins: ['italy'],
        cookTime: '10-15',
    },
    {
        id: '7',
        name: 'Chocolate',
        price: 2,
        favorite: false,
        stars: 5.0,
        imageUrl: 'assets/images/d15.jpg',
        origins: ['italy'],
        cookTime: '10-15',
    },
    {
        id: '8',
        name: 'Matcha',
        price: 2,
        favorite: false,
        stars: 5.0,
        imageUrl: 'assets/images/d9.jpg',
        origins: ['italy'],
        cookTime: '10-15',
    },
    {
        id: '9',
        name: 'Jam',
        price: 2,
        favorite: false,
        stars: 5.0,
        imageUrl: 'assets/images/d20.jpg',
        origins: ['italy'],
        cookTime: '15-20',
    },
    {
        id: '10',
        name: 'Glazed',
        price: 2,
        favorite: false,
        stars: 5.0,
        imageUrl: 'assets/images/d6.jpg',
        origins: ['italy'],
        cookTime: '10-15',
    },
    {
        id: '11',
        name: 'Homemade',
        price: 2,
        favorite: false,
        stars: 5.0,
        imageUrl: 'assets/images/d13.jpg',
        origins: ['italy'],
        cookTime: '10-15',
    },
    {
        id: '12',
        name: 'Millionaires',
        price: 2,
        favorite: false,
        stars: 5.0,
        imageUrl: 'assets/images/d14.jpg',
        origins: ['italy'],
        cookTime: '10-15',
    },
    {
        id: '13',
        name: 'Homer',
        price: 2,
        favorite: false,
        stars: 5.0,
        imageUrl: 'assets/images/d11.jpg',
        origins: ['italy'],
        cookTime: '10-15',
    },
    {
        id: '14',
        name: 'Chocolate',
        price: 2,
        favorite: false,
        stars: 5.0,
        imageUrl: 'assets/images/d19.jpg',
        origins: ['italy'],
        cookTime: '10-15',
    },
    {
        id: '15',
        name: 'Jam',
        price: 2,
        favorite: false,
        stars: 5.0,
        imageUrl: 'assets/images/d12.jpg',
        origins: ['italy'],
        cookTime: '10-15',
    },
    {
        id: '16',
        name: 'Perfect',
        price: 2,
        favorite: false,
        stars: 5.0,
        imageUrl: 'assets/images/d8.jpg',
        origins: ['italy'],
        cookTime: '10-15',
    },
    {
        id: '17',
        name: 'Chocolate',
        price: 2,
        favorite: false,
        stars: 5.0,
        imageUrl: 'assets/images/d2.jpg',
        origins: ['italy'],
        cookTime: '10-15',
    },
    {
        id: '18',
        name: 'Matcha',
        price: 2,
        favorite: false,
        stars: 5.0,
        imageUrl: 'assets/images/d16.jpg',
        origins: ['italy'],
        cookTime: '10-15',
    },
    {
        id: '19',
        name: 'Homer',
        price: 2,
        favorite: false,
        stars: 5.0,
        imageUrl: 'assets/images/d5.jpg',
        origins: ['italy'],
        cookTime: '10-15',
    },
    {
        id: '20',
        name: 'Suger',
        price: 2,
        favorite: false,
        stars: 5.0,
        imageUrl: 'assets/images/d22.jpg',
        origins: ['italy'],
        cookTime: '10-15',
    },
]

